name: 'setup_node_and_pnpm'
description: 'Setup Node.js and pnpm for GitHub Actions'

runs:
  using: 'composite'
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        cache-dependency-path: ${{ inputs.cache-dependency-path }}

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false