name: Pulumi - Update Infrastructure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        id: checkout

      - name: Install Node.js
        id: install-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        id: install-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.1

      - name: Install dependencies
        id: install-dependencies
        run: pnpm install
        working-directory: ./infra

      - name: Configure AWS Credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ vars.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run Pulumi
        id: run-pulumi
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: MuriloMorandi/stg
          work-dir: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
