name: Server Validation

on:
  pull_request:
    branches:
      - master
    types: [opened, reopened, labeled, unlabeled, synchronize]
    paths:
      - "server/**"
  workflow_dispatch:

jobs:
  build-server:
    name: Run build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: server/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: server

      - name: Build project
        run: pnpm run build
        working-directory: server

  test-server:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build-server

    services:
      postgres:
        image: postgres:13
        ports:
          - 5431:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: brevly_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: server/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: server

      - name: Run test
        run: pnpm run test
        working-directory: server
