name: Web Validation

on:
    pull_request:
        branches:
            - master
        paths:
            - "web/**"
    workflow_dispatch:

jobs:
    build-web:
        name: Run build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  version: 10
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: pnpm
                  cache-dependency-path: web/pnpm-lock.yaml

            - name: Install dependencies
              run: pnpm install --frozen-lockfile
              working-directory: web

            - name: Build project
              run: pnpm run build
              working-directory: server
