name: Deploy to Vercel

on:
  push:
    branches:
      - master
    paths:
      - "web/**"

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy-app-web:
    name: Run build
    runs-on: ubuntu-latest

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache-dependency-path: web/pnpm-lock.yaml

      - name: Install vercel
        run: npm install --global vercel@latest

      - name: Pull vercel config
        id: pull-vercel-config
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: web

      - name: Build app
        id: build-app
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: web

      - name: Deploy app
        id: deploy-app
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: web
